
# Adding different types of enviroments to get the best test coverage and to make sure that 
# the product is working and functiong as expected through out the SDLC.

dev:

#  dev env



qa: 

# qa env



stage:

# stage env


prod:

# production env

